name: 'Demo pipeline with deployment environments'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy in Env
        run: |
          echo "Hello world"